package builtins

var BuilinTypes = map[string]string{

	"co.int":           "fΦλ.lang.int",
	"co.float":         "fΦλ.lang.float",
	"co.bool":          "fΦλ.lang.bool",
	"co.string":        "fΦλ.lang.string",
	"co.char":          "fΦλ.lang.char",
	"co.double":        "fΦλ.lang.double",
	"co.byte":          "fΦλ.lang.byte",
	"co.short":         "fΦλ.lang.short",
	"co.bit":           "fΦλ.lang.bit",
	"co.long":          "fΦλ.lang.long",
	"co.void":          "fΦλ.lang.void",
	"co.cint":          "fΦλ.lang.cint",
	"co.cfloat":        "fΦλ.lang.cfloat",
	"co.cdouble":       "fΦλ.lang.cdouble",
	"co.MatchBindings": "fΦλ.lang.MatchBindings",
	"co.untyped":       "fΦλ.lang.untyped",
	"co.uninit":        "fΦλ.lang.uninit",
	"co.any":           "fΦλ.lang.any",
	"co.function":      "fΦλ.lang.function",
	"co.error":         "fΦλ.lang.error",
	"co.AbstractError": "fΦλ.lang.AbstractError",
}

var BuitinInternal = map[string]string{
	"co.literal":        "fΦλ.lang.literal",
	"co.value":          "fΦλ.lang.value",
	"co.condition":      "fΦλ.lang.condition",
	"co.builtinproto":   "fΦλ.lang.builtinproto",
	"co.adtType":        "fΦλ.lang.adtType",
	"co.functionType":   "fΦλ.lang.functionType",
	"co.symbol":         "fΦλ.lang.symbol",
	"co.generic":        "fΦλ.lang.generic",
	"co.specializetype": "fΦλ.lang.specializetype",
}

var BuiltinKinds = map[string]string{
	"co.struct":    "fΦλ.lang.struct",
	"co.enum":      "fΦλ.lang.enum",
	"co.union":     "fΦλ.lang.union",
	"co.class":     "fΦλ.lang.class",
	"co.interface": "fΦλ.lang.interface",
	"co.trait":     "fΦλ.lang.trait",
	"co.module":    "fΦλ.lang.module",
	"co.package":   "fΦλ.lang.package",
	"co.object":    "fΦλ.lang.object",
	"co.mixin":     "fΦλ.lang.mixin",
	"co.signature": "fΦλ.lang.signature",
	"co.typeclass": "fΦλ.lang.typeclass",
	"co.instance":  "fΦλ.lang.instance",
	"co.Matcher":   "fΦλ.lang.Matdher",
	"co.Extension": "fΦλ.lang.Extension",
	"co.unit":      "fΦλ.lang.unit",
	"co.component": "fΦλ.lang.component",
}

var TypeForms = map[string]string{
	"co.type":           "fΦλ.lang.type",
	"co.newtype":        "fΦλ.lang.newtype",
	"co.opaquetype":     "fΦλ.lang.opaquetype",
	"co.dependenttype":  "fΦλ.lang.dependenttype",
	"co.predicatedtype": "fΦλ.lang.predicatedtype",
	"co.refinementType": "fΦλ.lang.refinementType",
	"co.data":           "fΦλ.lang.data",
	"co.variants":       "fΦλ.lang.variants",
	"co.associatedtype": "fΦλ.lang.associatedtype",
	"co.tag":            "fΦλ.lang.tag",
	"co.delegate":       "fΦλ.lang.delegate",
	"co.hokrlt":         "fΦλ.lang.hokrlt",
	"co.supertype":      "fΦλ.lang.supertype",
	"co.subtype":        "fΦλ.lang.subtype",
	"co.derivedtype":    "fΦλ.lang.derivedtype",
	"co.polymorphic":    "fΦλ.lang.polymorphic",
	"co.kind":           "fΦλ.lang.kind",
	"co.shape":          "fΦλ.lang.shape",
}

var BuilinDirectives = map[string]string{
	"@co.pdap.threadpool":    "@co.pdap.threadpool",
	"@co.pdap.schedularpool": "@co.pdap.schedularpool",

	"@co.ddap.import":          "@co.ddap.import",
	"@co.ddap.dynamicruntime":  "@co.ddap.dynamicruntime",
	"@co.ddap.use":             "@co.ddap.use",
	"@co.ddap.alias":           "@co.ddap.alias",
	"@co.ddap.dynamicdispatch": "@co.ddap.dynamicdispatch",
	"@co.ddap.overload":        "@co.ddap.overload",

	"@co.dap.extend":         "@co.dap.extend",
	"@co.dap.template":       "@co.dap.template",
	"@co.dap.macro":          "@co.dap.macro",
	"@co.dap.operator":       "@co.dap.operator",
	"@co.dap.annotation":     "@co.dap.annotation",
	"@co.dap.library":        "@co.dap.library",
	"@co.dap.native":         "@co.dap.native",
	"@co.dap.cabi":           "@co.dap.cabi",
	"@co.dap.class":          "@co.dap.class",
	"@co.dap.static":         "@co.dap.static",
	"@co.dap.object":         "@co.dap.object",
	"@co.dap.inline":         "@co.dap.inline",
	"@co.dap.ctfe":           "@co.dap.ctfe",
	"@co.dap.friend":         "@co.dap.friend",
	"@co.dap.sealed":         "@co.dap.sealed",
	"@co.dap.extension":      "@co.dap.extension",
	"@co.dap.override":       "@co.dap.override",
	"@co.dap.implement":      "@co.dap.implement",
	"@co.dap.virtual":        "@co.dap.virtual",
	"@co.dap.abstract":       "@co.dap.abstract",
	"@co.dap.delegate":       "@co.dap.delegate",
	"@co.dap.typeclass":      "@co.dap.typeclass",
	"@co.dap.matcher":        "@co.dap.matcher",
	"@co.dap.constructor":    "@co.dap.constructor",
	"@co.dap.oops":           "@co.dap.oops",
	"@co.dap.extends":        "@co.dap.extends",
	"@co.dap.hokrlt":         "@co.dap.hokrlt",
	"@co.dap.indexer":        "@co.dap.indexer",
	"@co.dap.generic":        "@co.dap.generic",
	"@co.dap.comptime":       "@co.dap.comptime",
	"@co.dap.typefromvalue":  "@co.dap.typefromvalue",
	"@co.dap.local":          "@co.dap.local",
	"@co.dap.private":        "@co.dap.private",
	"@co.dap.public":         "@co.dap.public",
	"@co.dap.compose":        "@co.dap.compose",
	"@co.dap.guard":          "@co.dap.guard",
	"@co.dap.package":        "@co.dap.package",
	"@co.dap.protected":      "@co.dap.protected",
	"@co.dap.internal":       "@co.dap.internal",
	"@co.dap.export":         "@co.dap.export",
	"@co.dap.eager":          "@co.dap.eager",
	"@co.dap.lazy":           "@co.dap.lazy",
	"@co.dap.packed":         "@co.dap.packed",
	"@co.dap.declare":        "@co.dap.declare",
	"@co.dap.implementation": "@co.dap.implementation",
	"@co.dap.simd":           "@co.dap.simd",
	"@co.dap.reflection":     "@co.dap.reflection",
	"@co.dap.mop":            "@co.dap.mop",
	"@co.dap.nested":         "@co.dap.nested",
	"@co.dap.inner":          "@co.dap.inner",
	"@co.dap.final":          "@co.dap.final",
	"@co.dap.const":          "@co.dap.const",
	"@co.dap.decorator":      "@co.dap.decorator",
	"@co.dap.specialize":     "@co.dap.specialize",
	"@co.dap.scope":          "@co.dap.scope",
	"@co.dap.symbol":         "@co.dap.symbol",
	"@co.dap.with":           "@co.dap.with",

	"@co.dap.before":         "@co.dap.before",
	"@co.dap.after":          "@co.dap.after",
	"@co.dap.around":         "@co.dap.around",
	"@co.dap.effects":        "@co.dap.effects",
	"@co.dap.onEffect":       "@co.dap.onEffect",
	"@co.dap.defer":          "@co.dap.defer",
	"@co.dap.callable":       "@co.dap.callable",
	"@co.dap.executionmodel": "@co.dap.executionmodel",
}

var BuiltinComponentKinds = map[string]string{
	"dynamicvmrt": "dynamicvmrt",
	"application": "application",
	"native":      "native",
	"operators":   "operators",
	"packaged":    "packaged",
}

var Special_methods []string = []string{
	"@@new",
	"@@init",
}

// Reserved_lu maps reserved language keywords to their TokenKind.
var Reserved_lu []string = []string{
	"co",
	"this",
	"fΦλ",
}
