package builtins

var BuilinTypes = map[string]string{

	"co.int":           "fΦλ.lang.int",
	"co.float":         "fΦλ.lang.float",
	"co.bool":          "fΦλ.lang.bool",
	"co.string":        "fΦλ.lang.string",
	"co.char":          "fΦλ.lang.char",
	"co.double":        "fΦλ.lang.double",
	"co.byte":          "fΦλ.lang.byte",
	"co.short":         "fΦλ.lang.short",
	"co.bit":           "fΦλ.lang.bit",
	"co.long":          "fΦλ.lang.long",
	"co.void":          "fΦλ.lang.void",
	"co.cint":          "fΦλ.lang.cint",
	"co.cfloat":        "fΦλ.lang.cfloat",
	"co.cchar":         "fΦλ.lang.cchar",
	"co.cdouble":       "fΦλ.lang.cdouble",
	"co.clong":         "fΦλ.lang.clong",
	"co.MatchBindings": "fΦλ.lang.MatchBindings",
	"co.untyped":       "fΦλ.lang.untyped",
	"co.uninit":        "fΦλ.lang.uninit",
	"co.any":           "fΦλ.lang.any",
	"co.function":      "fΦλ.lang.function",
	"co.error":         "fΦλ.lang.error",
	"co.AbstractError": "fΦλ.lang.AbstractError",
}

var BuitinInternal = map[string]string{
	"co.literal":        "fΦλ.lang.literal",
	"co.value":          "fΦλ.lang.value",
	"co.condition":      "fΦλ.lang.condition",
	"co.builtinproto":   "fΦλ.lang.builtinproto",
	"co.adtType":        "fΦλ.lang.adtType",
	"co.functionType":   "fΦλ.lang.functionType",
	"co.symbol":         "fΦλ.lang.symbol",
	"co.generic":        "fΦλ.lang.generic",
	"co.specializetype": "fΦλ.lang.specializetype",
}

var BuiltinKinds = map[string]string{
	"co.struct":    "fΦλ.lang.struct",
	"co.enum":      "fΦλ.lang.enum",
	"co.union":     "fΦλ.lang.union",
	"co.class":     "fΦλ.lang.class",
	"co.interface": "fΦλ.lang.interface",
	"co.trait":     "fΦλ.lang.trait",
	"co.module":    "fΦλ.lang.module",
	"co.package":   "fΦλ.lang.package",
	"co.object":    "fΦλ.lang.object",
	"co.mixin":     "fΦλ.lang.mixin",
	"co.signature": "fΦλ.lang.signature",
	"co.typeclass": "fΦλ.lang.typeclass",
	"co.instance":  "fΦλ.lang.instance",
	"co.Matcher":   "fΦλ.lang.Matdher",
	"co.Extension": "fΦλ.lang.Extension",
	"co.unit":      "fΦλ.lang.unit",
	"co.component": "fΦλ.lang.component",
}

var TypeForms = map[string]string{
	"co.type":           "fΦλ.lang.type",
	"co.newtype":        "fΦλ.lang.newtype",
	"co.opaquetype":     "fΦλ.lang.opaquetype",
	"co.dependenttype":  "fΦλ.lang.dependenttype",
	"co.predicatedtype": "fΦλ.lang.predicatedtype",
	"co.refinementType": "fΦλ.lang.refinementType",
	"co.data":           "fΦλ.lang.data",
	"co.variants":       "fΦλ.lang.variants",
	"co.associatedtype": "fΦλ.lang.associatedtype",
	"co.tag":            "fΦλ.lang.tag",
	"co.delegate":       "fΦλ.lang.delegate",
	"co.hokrlt":         "fΦλ.lang.hokrlt",
	"co.supertype":      "fΦλ.lang.supertype",
	"co.subtype":        "fΦλ.lang.subtype",
	"co.derivedtype":    "fΦλ.lang.derivedtype",
	"co.polymorphic":    "fΦλ.lang.polymorphic",
	"co.kind":           "fΦλ.lang.kind",
	"co.shape":          "fΦλ.lang.shape",
}

type DDAPKind string

const (
	PragmaKind     DDAPKind = "pragma"
	DirectiveKind  DDAPKind = "directive"
	AnnotationKind DDAPKind = "annotation"
	DecoratorKind  DDAPKind = "decorator"
)

var BuilinDirectives = map[string]DDAPKind{
	"@co.pdap.threadpool":    PragmaKind,
	"@co.pdap.schedularpool": PragmaKind,

	"@co.ddap.import":          DirectiveKind,
	"@co.ddap.dynamicruntime":  DirectiveKind,
	"@co.ddap.use":             DirectiveKind,
	"@co.ddap.alias":           DirectiveKind,
	"@co.ddap.dynamicdispatch": DirectiveKind,
	"@co.ddap.overload":        DirectiveKind,

	"@co.dap.extend":         AnnotationKind,
	"@co.dap.template":       AnnotationKind,
	"@co.dap.macro":          AnnotationKind,
	"@co.dap.operator":       AnnotationKind,
	"@co.dap.annotation":     AnnotationKind,
	"@co.dap.library":        AnnotationKind,
	"@co.dap.native":         AnnotationKind,
	"@co.dap.cabi":           AnnotationKind,
	"@co.dap.class":          AnnotationKind,
	"@co.dap.static":         AnnotationKind,
	"@co.dap.object":         AnnotationKind,
	"@co.dap.inline":         AnnotationKind,
	"@co.dap.ctfe":           AnnotationKind,
	"@co.dap.friend":         AnnotationKind,
	"@co.dap.sealed":         AnnotationKind,
	"@co.dap.extension":      AnnotationKind,
	"@co.dap.override":       AnnotationKind,
	"@co.dap.implement":      AnnotationKind,
	"@co.dap.virtual":        AnnotationKind,
	"@co.dap.abstract":       AnnotationKind,
	"@co.dap.delegate":       AnnotationKind,
	"@co.dap.typeclass":      AnnotationKind,
	"@co.dap.matcher":        AnnotationKind,
	"@co.dap.constructor":    AnnotationKind,
	"@co.dap.oops":           AnnotationKind,
	"@co.dap.extends":        AnnotationKind,
	"@co.dap.hokrlt":         AnnotationKind,
	"@co.dap.indexer":        AnnotationKind,
	"@co.dap.generic":        AnnotationKind,
	"@co.dap.comptime":       AnnotationKind,
	"@co.dap.typefromvalue":  AnnotationKind,
	"@co.dap.local":          AnnotationKind,
	"@co.dap.private":        AnnotationKind,
	"@co.dap.public":         AnnotationKind,
	"@co.dap.compose":        AnnotationKind,
	"@co.dap.guard":          AnnotationKind,
	"@co.dap.package":        AnnotationKind,
	"@co.dap.protected":      AnnotationKind,
	"@co.dap.internal":       AnnotationKind,
	"@co.dap.export":         AnnotationKind,
	"@co.dap.eager":          AnnotationKind,
	"@co.dap.lazy":           DecoratorKind,
	"@co.dap.packed":         AnnotationKind,
	"@co.dap.declare":        AnnotationKind,
	"@co.dap.implementation": AnnotationKind,
	"@co.dap.simd":           AnnotationKind,
	"@co.dap.reflection":     AnnotationKind,
	"@co.dap.mop":            AnnotationKind,
	"@co.dap.nested":         AnnotationKind,
	"@co.dap.inner":          AnnotationKind,
	"@co.dap.final":          AnnotationKind,
	"@co.dap.const":          AnnotationKind,
	"@co.dap.decorator":      AnnotationKind,
	"@co.dap.specialize":     AnnotationKind,
	"@co.dap.scope":          AnnotationKind,
	"@co.dap.symbol":         AnnotationKind,
	"@co.dap.with":           AnnotationKind,

	"@co.dap.before":         DecoratorKind,
	"@co.dap.after":          DecoratorKind,
	"@co.dap.around":         DecoratorKind,
	"@co.dap.effects":        DecoratorKind,
	"@co.dap.onEffect":       DecoratorKind,
	"@co.dap.defer":          DecoratorKind,
	"@co.dap.callable":       DecoratorKind,
	"@co.dap.executionmodel": DecoratorKind,
}

var BuiltinComponentKinds = map[string]string{
	"dynamicvmrt": "dynamicvmrt",
	"application": "application",
	"native":      "native",
	"operators":   "operators",
	"packaged":    "packaged",
}

var Special_methods []string = []string{
	"@@new",
	"@@init",
}

// Reserved_lu maps reserved language keywords to their TokenKind.
var Reserved_lu []string = []string{
	"co",
	"this",
	"fΦλ",
}

var BuiltinPackages map[string][]string = map[string][]string{
	"co":             {"fΦλ.lang", "fΦλ.net", "fΦλ.core"},
	"co.const":       {"fΦλ.const"},
	"co.sys":         {"fΦλ.sys"},
	"co.os":          {"fΦλ.os"},
	"co.meta":        {"fΦλ.meta"},
	"co.native":      {"fΦλ.native"},
	"co.in":          {"fΦλ.in"},
	"co.out":         {"fΦλ.out"},
	"co.regex":       {"fΦλ.regex"},
	"co.crypto":      {"fΦλ.crypto"},
	"co.dap":         {"fΦλ.dap"},
	"co.ddap":        {"fΦλ.ddap"},
	"co.pdap":        {"fΦλ.pdap"},
	"co.encoding":    {"fΦλ.encoding"},
	"co.utils":       {"fΦλ.utils"},
	"co.dynamic":     {"fΦλ.dynamic"},
	"co.runtime":     {"fΦλ.runtime"},
	"co.compiletime": {"fΦλ.compiletime"},
	"co.macro":       {"fΦλ.macro"},
	"co.pattern":     {"fΦλ.pattern"},
	"co.control":     {"fΦλ.control"},
	"co.cpca":        {"fΦλ.cpca"},
	"co.operator":    {"fΦλ.operator"},
	"co.hw":          {"fΦλ.hw"},
	"co.stex":        {"fΦλ.stex"},
}
